shell /usr/bin/fish
cursor_trail 3
# font_family      JetBrainsMonoNL Nerd Font
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

background_opacity 0.90
dynamic_background_opacity yes
window_padding_width 5 0 10 10
font_size 20.0
confirm_os_window_close 0
enable_audio_bell no


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
